### ISSUE TITLE
SimpleInputStream builder does not work.

### ISSUE THREAD

**Issue by jamesdbaker** [annot8/annot8-default-impl-deprecated#4]
https://github.com/annot8/annot8-default-impl/blob/6ad55147b800b9fe2ea9e96da1c47f1ce5077242/src/main/java/io/annot8/defaultimpl/content/SimpleInputStream.java#L66-L80

This inner class refers to SimpleText, when it should be SimpleInputStream. Looks like a copy and paste issue.

**Comment by chrisflatley** [comment]
Fixes.. this was a copy and paste error as my mind was on the Content<D> vs ContentBuilder<Supplier<D>> issues. 

I've updated the contentbuilder and content to be a supplier by default now, and fixed this issue.
